config/routes.rb
Rails.application.routes.draw do

  resources :blogs, only: [:index, :new, :create, :edit, :update ,:destroy] do
    collection do
      post :confirm
    end
  end
  
  match "blogs/new", :via => :post
  
  root 'blogs#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
    validates :content, presence: true
    validates :content, length: { in: 1..255 } 
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blogs, only: [:edit, :update, :destroy]
  
  def index
    @blogs = Blog.all
  end

  def new
    if params[:back]
      @blogs = Blog.new(blogs_params)
    else
      @blogs = Blog.new
    end
  end

  def create
    @blogs = Blog.new(blogs_params)
    if @blogs.save
     redirect_to blogs_path, notice: "ツイートを作成しました！"
    else
      render action: 'new'
    end
  end
  
  def edit
  end
  
  def update
    @blogs.update(blogs_params)
    redirect_to blogs_path, notice: "ツイートを更新しました！"
  end
  
  def destroy
    @blogs.destroy
    redirect_to blogs_path, notice: "ツイートを削除しました！"
  end
  
  def confirm
    @blogs = Blog.new(blogs_params)
    render :new if @blogs.invalid?
  end
  
   private
    def blogs_params
      params.require(:blog).permit(:content)
    end
    
    def set_blogs
    @blogs = Blog.find(params[:id])
    end
    
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blogs, url: choose_new_or_edit) do |f| %>
  <% if @blogs.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blogs.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @blogs.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :content %>
  <%= f.text_field :content, class: 'form-control' %>
  <br>
　<%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

<%= link_to "ツイート一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容で、送信する。</h3>
    <%= form_for(@blogs) do |f| %>
      <%= f.hidden_field :content %>
      <p>本文:<%= @blogs.content %></p>
      <%= f.submit "登録",class: 'btn btn-primary btn-block'  %>
    <% end %>
    <%= form_for(@blogs, url: new_blog_path) do |f| %>
      <%= f.hidden_field :content %>
      <%= f.submit "もどる",name: 'back', class: 'btn btn-default btn-block'  %>
    <% end %>
  </div>
</div>

app/views/blogs/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ツイートを編集する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/blogs/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    <h1>ツイート一覧</h1>
      <%= link_to "ツイートを作成する", new_blog_path, class: 'btn btn-default' %>
    <% @blogs.each do |blog| %>
    <div class="row">
      <p><%= blog.content %></p>
      <%= link_to "編集", edit_blog_path(blog.id), class: 'btn btn-default btn-sm btn-success' %>
      <%= link_to "削除", blog_path(blog.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
    </div>
    <% end %>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ツイートを作成する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <header>
    <ul>
      <li><%= link_to "ホーム", root_path %></li>
      <li><a href="#">通知</a></li>
      <li><a href="#">メッセージ</a></li>
      <li><%= link_to "ツイートする", new_blog_path %></li>
      <li><%= link_to "ツイート一覧", blogs_path %></li>
    </ul>
  </header>

<%= yield %>


<div id="page-top-btn" class="page-top-btn">
    <p><a class="move-page-top" id="move-page-top">▲</a></p>
</div>

  <footer>
    <p>Made by T.Y</p>
    <p>© 2015-2016 Copyright T.Y</p>
  </footer>

</body>
</html>

app/views/top/index.html.erb
<!DOCTYPE html>
<html lang="ja">
    
<head>
    <meta charset="UTF-8">
    <title>Twitter</title>
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="normalize.css">
</head>

<body>
    

</body>
</html>